Repository mateuseap/kubernetes-calculator, pull requests merged in 2023-12, with the labels that each got.

#2 feature: creating mock for instances payload
  README.md
  app.py
  aws/pricing.py
  aws/resource_reservation.py
  data/eni-max-pods.txt
  data/instance.py
  data/resource_convertion.py
  requirements.txt
Labels: enhancement

#3 feature: create frontend and update documentation
  .github/workflows/frontend-deploy.yml
  README.md
  app.py
  backend/.gitignore
  backend/app.py
  backend/aws/pricing.py
  backend/aws/resource_reservation.py
  backend/data/eni-max-pods.txt
  backend/data/instance.py
  backend/data/resource_convertion.py
  backend/requirements.txt
  frontend/.eslintrc.cjs
  frontend/.gitignore
  frontend/index.html
  frontend/package-lock.json
  frontend/package.json
  frontend/postcss.config.js
  frontend/public/CNAME
  frontend/public/calculator.ico
  frontend/src/App.tsx
  frontend/src/index.css
  frontend/src/main.tsx
  frontend/src/pages/Home/index.tsx
  frontend/src/router.tsx
  frontend/src/vite-env.d.ts
  frontend/tailwind.config.js
  frontend/tsconfig.json
  frontend/tsconfig.node.json
  frontend/vite.config.ts
Labels: enhancement

#4 fix: resolve missing package and adjust `frontend-deploy.yml` workflow trigger
  .github/workflows/frontend-deploy.yml
  frontend/package-lock.json
  frontend/package.json
Labels: bug

#5 feature: connect frontend with backend and fix some bugs
  .github/workflows/frontend-deploy.yml
  README.md
  backend/app.py
  backend/data/instance.py
  backend/requirements.txt
  frontend/.env.template
  frontend/.gitignore
  frontend/package-lock.json
  frontend/package.json
  frontend/src/App.tsx
  frontend/src/components/InstancesTable/index.tsx
  frontend/src/components/RangeSliders/index.tsx
  frontend/src/pages/Home/index.tsx
  frontend/src/services/api.ts
  frontend/src/types/index.d.ts
  frontend/vite.env.d.ts
Labels: bug, enhancement

#6 fix: adjust `frontend-deploy.yml` GitHub workflow
  .github/workflows/frontend-deploy.yml
Labels: bug

#7 feature: update `frontend-deploy.yml` GitHub workflow
  .github/workflows/frontend-deploy.yml
Labels: enhancement

#8 feature: trigger `frontend-deploy.yml` GitHub workflow on workflow file change
  .github/workflows/frontend-deploy.yml
Labels: enhancement
